### ISSUE TITLE
toolbox space button

### ISSUE THREAD

**Issue by DEvil0000** [see-base/spaceOpenCloseButton#1]
which one is the fork?
merge code?

https://github.com/ToolboxBodensee/spacebutton

**Comment by DO1JLR** [comment]
they are individual.

one is running in see-base.

the other in toolbox.

Two different repos for two different spaces...

**Comment by DEvil0000** [comment]
that does not make sense since its doing the same thing...Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: L3D <notifications@github.com> 
Datum: 23.09.2019  20:04  (GMT+01:00) 
An: see-base/spaceOpenCloseButton <spaceOpenCloseButton@noreply.github.com> 
Cc: "A. Binzxxxxxx" <alexander@binzberger.de>, Author <author@noreply.github.com> 
Betreff: Re: [see-base/spaceOpenCloseButton] toolbox space button (#1) 

they are individual.
one is running in see-base.
the other in toolbox.
Two different repos for two different spaces...

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/see-base/spaceOpenCloseButton/issues/1?email_source=notifications\u0026email_token=AAZQPLVINGV7J2HW747ABRLQLEAK7A5CNFSM4IZNETT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7LXYYQ#issuecomment-534215778",
"url": "https://github.com/see-base/spaceOpenCloseButton/issues/1?email_source=notifications\u0026email_token=AAZQPLVINGV7J2HW747ABRLQLEAK7A5CNFSM4IZNETT2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7LXYYQ#issuecomment-534215778",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by DO1JLR** [comment]
ja... mehr oder weniger.

aber... dann wird da doch noch mal dran rum gefrickelt und schwups hat man wieder inkosistente daten...

und da hab ich irgendwann das zweite repo spendirt!
